; Jasmin JBC assembler code generated by AliaCodeGenerator
.class public Test.j
.super java/lang/Object

.method public <init>()V
   aload_0
   invokenonvirtual java/lang/Object/<init>()V
   return
.end method

.method public static main([Ljava/lang/String;)V
   .limit stack 20
   .limit locals 20
   
   iconst_5

   istore_0                  ; store value into x
     iload_0
     iconst_3

     if_icmplt $+7 ; Go to iconst_1 if it is true
     iconst_0
     goto $+4 ; Go to the line after iconst_1
     iconst_1
     ifeq ELSE0
     bipush 50
     istore_0                  ; store value into x
     goto NEXT1
     ELSE0:
     NEXT1:
   getstatic java/lang/System/out Ljava/io/PrintStream;
   iload_0
   invokevirtual java/io/PrintStream/println(I)V ; add right constant pool reference bytes for println

   return
.end method